# Generated by Django 5.2.4 on 2025-07-15 18:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate (VEF per USD)')),
                ('source', models.CharField(choices=[('BCV_SCRAPER', 'BCV Scraper'), ('MANUAL_INPUT', 'Manual Input')], max_length=20, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalExchangeRate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate (VEF per USD)')),
                ('source', models.CharField(choices=[('BCV_SCRAPER', 'BCV Scraper'), ('MANUAL_INPUT', 'Manual Input')], max_length=20, verbose_name='Source')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Exchange Rate',
                'verbose_name_plural': 'historical Exchange Rates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
