# Generated by Django 5.2.4 on 2025-07-18 06:16

import encrypted_model_fields.fields
import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification_number',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True, error_messages={'unique': 'A user with that identification number already exists.'}, help_text='Formato: L-NNNNNNNN (ej. V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', unique=True, validators=[utils.validators.validate_natural_person_id], verbose_name='identification number'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='identification_number',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True, error_messages={'unique': 'A user with that identification number already exists.'}, help_text='Formato: L-NNNNNNNN (ej. V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', validators=[utils.validators.validate_natural_person_id], verbose_name='identification number'),
        ),
    ]
