# Generated by Django 5.2.4 on 2025-07-15 18:13

import django.db.models.deletion
import simple_history.models
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[utils.validators.validate_full_name], verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Enter the 11-digit cell phone number. It will be formatted automatically as (04XX) XXX-XXXX.', max_length=20, validators=[utils.validators.validate_venezuelan_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('identification_number', models.CharField(help_text='Formato: L-NNNNNNNN (ej., V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', max_length=20, validators=[utils.validators.validate_natural_person_id], verbose_name='Identification Number')),
                ('phone_hash', models.CharField(editable=False, max_length=64)),
                ('email_hash', models.CharField(editable=False, max_length=64)),
                ('identification_number_hash', models.CharField(editable=False, max_length=64)),
                ('ticket_count', models.PositiveIntegerField(default=1, verbose_name='Ticket Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalParticipation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, validators=[utils.validators.validate_full_name], verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Enter the 11-digit cell phone number. It will be formatted automatically as (04XX) XXX-XXXX.', max_length=20, validators=[utils.validators.validate_venezuelan_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('identification_number', models.CharField(help_text='Formato: L-NNNNNNNN (ej., V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', max_length=20, validators=[utils.validators.validate_natural_person_id], verbose_name='Identification Number')),
                ('phone_hash', models.CharField(editable=False, max_length=64)),
                ('email_hash', models.CharField(editable=False, max_length=64)),
                ('identification_number_hash', models.CharField(editable=False, max_length=64)),
                ('ticket_count', models.PositiveIntegerField(default=1, verbose_name='Ticket Count')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Participation',
                'verbose_name_plural': 'historical Participations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
