# Generated by Django 5.2.4 on 2025-07-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipation',
            name='raffle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='raffles.raffle', verbose_name='Raffle'),
        ),
        migrations.AddField(
            model_name='participation',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='raffles.raffle', verbose_name='Raffle'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['raffle', 'identification_number_hash', 'phone_hash', 'email_hash'], name='ticket_lookup_idx'),
        ),
    ]
