# Generated by Django 5.2.4 on 2025-07-18 06:16

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipation',
            name='identification_number',
            field=models.CharField(help_text='Formato: L-NNNNNNNN (ej. V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', max_length=20, validators=[utils.validators.validate_natural_person_id], verbose_name='Identification Number'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='identification_number',
            field=models.CharField(help_text='Formato: L-NNNNNNNN (ej. V-12345678). Se formateará automáticamente.<br><b>V</b>: Venezolano | <b>E</b>: Extranjero | <b>P</b>: Pasaporte', max_length=20, validators=[utils.validators.validate_natural_person_id], verbose_name='Identification Number'),
        ),
    ]
