# Generated by Django 5.2.4 on 2025-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_alter_historicalparticipation_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipation',
            name='phone',
            field=models.CharField(help_text='Enter the 11-digit cell phone number.', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='phone',
            field=models.CharField(help_text='Enter the 11-digit cell phone number.', max_length=20, verbose_name='Phone Number'),
        ),
    ]
