# Generated by Django 5.2.4 on 2025-07-15 18:13

import datetime
import django.core.validators
import django.db.models.deletion
import simple_history.models
import utils.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRaffle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for URL. Auto-generated from title.', max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promotional_message', models.TextField(blank=True, help_text="Catchy text to display when this is the main raffle. Required if 'Is Main Raffle?' is checked.", verbose_name='Promotional Message')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('VEF', 'Venezuelan Bolívar')], default='USD', max_length=3, verbose_name='Currency')),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Price in the selected currency.', max_digits=10, verbose_name='Ticket Price')),
                ('total_tickets', models.PositiveIntegerField(verbose_name='Total Tickets')),
                ('min_ticket_purchase', models.PositiveIntegerField(default=1, help_text='Minimum number of tickets a participant must buy at once.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Ticket Purchase')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PROCESSING_WINNERS', 'Processing Winners'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Check this to make the raffle visible to participants on the website.', verbose_name='Is Publicly Visible?')),
                ('image', models.TextField(help_text='Banner image for the raffle.', max_length=100, verbose_name='Main Image')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional. Leave blank if the raffle ends based on manual decision or ticket sales.', null=True, verbose_name='End Date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Raffle',
                'verbose_name_plural': 'historical Raffles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order of importance for display (1 = most important).', verbose_name='Display Order')),
                ('level_title', models.CharField(blank=True, help_text="E.g., 'Grand Prize', 'Second Prize', 'Consolation Prize'.", max_length=100, verbose_name='Prize Level Title')),
                ('name', models.CharField(max_length=100, verbose_name='Prize Name')),
                ('description', models.TextField(blank=True, verbose_name='Prize Description')),
                ('image', models.ImageField(blank=True, help_text='Promotional image of the prize.', null=True, upload_to=utils.storage.prize_image_path, verbose_name='Prize Image')),
                ('delivered_image', models.ImageField(blank=True, help_text='Photo of the winner with their prize.', null=True, upload_to=utils.storage.winner_image_path, verbose_name='Winner Photo')),
                ('winner_ticket_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Winner Ticket Number')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('winner_participation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_prizes', to='participants.participation', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prizes',
                'ordering': ['raffle', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDraw',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lottery_name', models.CharField(default='Lotería del Táchira', max_length=100, verbose_name='Lottery Name')),
                ('draw_time', models.DateTimeField(help_text='Date and time of the external lottery draw.', verbose_name='Draw Time')),
                ('winning_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Winning Number')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('ROLLED_OVER', 'Rolled Over')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='raffles.prize', verbose_name='Prize')),
            ],
            options={
                'verbose_name': 'historical Draw',
                'verbose_name_plural': 'historical Draws',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique identifier for URL. Auto-generated from title.', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promotional_message', models.TextField(blank=True, help_text="Catchy text to display when this is the main raffle. Required if 'Is Main Raffle?' is checked.", verbose_name='Promotional Message')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('VEF', 'Venezuelan Bolívar')], default='USD', max_length=3, verbose_name='Currency')),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Price in the selected currency.', max_digits=10, verbose_name='Ticket Price')),
                ('total_tickets', models.PositiveIntegerField(verbose_name='Total Tickets')),
                ('min_ticket_purchase', models.PositiveIntegerField(default=1, help_text='Minimum number of tickets a participant must buy at once.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum Ticket Purchase')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PROCESSING_WINNERS', 'Processing Winners'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Check this to make the raffle visible to participants on the website.', verbose_name='Is Publicly Visible?')),
                ('image', models.ImageField(help_text='Banner image for the raffle.', upload_to=utils.storage.raffle_banner_path, verbose_name='Main Image')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional. Leave blank if the raffle ends based on manual decision or ticket sales.', null=True, verbose_name='End Date')),
                ('available_payment_methods', models.ManyToManyField(help_text='Select the payment methods available for this raffle.', to='payments.paymentmethod', verbose_name='Available Payment Methods')),
            ],
            options={
                'verbose_name': 'Raffle',
                'verbose_name_plural': 'Raffles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='prize',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='raffles.raffle', verbose_name='Raffle'),
        ),
        migrations.CreateModel(
            name='HistoricalPrize',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=1, help_text='Order of importance for display (1 = most important).', verbose_name='Display Order')),
                ('level_title', models.CharField(blank=True, help_text="E.g., 'Grand Prize', 'Second Prize', 'Consolation Prize'.", max_length=100, verbose_name='Prize Level Title')),
                ('name', models.CharField(max_length=100, verbose_name='Prize Name')),
                ('description', models.TextField(blank=True, verbose_name='Prize Description')),
                ('image', models.TextField(blank=True, help_text='Promotional image of the prize.', max_length=100, null=True, verbose_name='Prize Image')),
                ('delivered_image', models.TextField(blank=True, help_text='Photo of the winner with their prize.', max_length=100, null=True, verbose_name='Winner Photo')),
                ('winner_ticket_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Winner Ticket Number')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('winner_participation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='participants.participation', verbose_name='Winner')),
                ('raffle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='raffles.raffle', verbose_name='Raffle')),
            ],
            options={
                'verbose_name': 'historical Prize',
                'verbose_name_plural': 'historical Prizes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_name', models.CharField(default='Lotería del Táchira', max_length=100, verbose_name='Lottery Name')),
                ('draw_time', models.DateTimeField(help_text='Date and time of the external lottery draw.', verbose_name='Draw Time')),
                ('winning_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Winning Number')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('ROLLED_OVER', 'Rolled Over')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='raffles.prize', verbose_name='Prize')),
            ],
            options={
                'verbose_name': 'Draw',
                'verbose_name_plural': 'Draws',
                'ordering': ['-draw_time'],
                'indexes': [models.Index(fields=['prize', 'draw_time'], name='raffles_dra_prize_i_a1ae5f_idx'), models.Index(fields=['status'], name='raffles_dra_status_b8e065_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='raffle',
            index=models.Index(fields=['slug'], name='raffles_raf_slug_bfcc47_idx'),
        ),
        migrations.AddIndex(
            model_name='raffle',
            index=models.Index(fields=['is_active', 'end_date'], name='raffles_raf_is_acti_f237bd_idx'),
        ),
        migrations.AddIndex(
            model_name='prize',
            index=models.Index(fields=['raffle', 'display_order'], name='raffles_pri_raffle__7e454b_idx'),
        ),
    ]
