# Generated by Django 5.2.4 on 2025-07-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalraffle',
            name='promotional_message',
            field=models.TextField(blank=True, help_text='Catchy text to display when this is the main raffle.', verbose_name='Promotional Message'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='promotional_message',
            field=models.TextField(blank=True, help_text='Catchy text to display when this is the main raffle.', verbose_name='Promotional Message'),
        ),
    ]
