# Generated by Django 5.2.4 on 2025-07-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Global Audit Log',
                'verbose_name_plural': 'Global Audit Logs',
                'managed': False,
            },
        ),
    ]
