# Generated by Django 5.2.4 on 2025-07-15 18:13

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Bank Code')),
                ('name', models.CharField(max_length=100, verbose_name='Bank Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('PAGO_MOVIL', 'Mobile Payment'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('TRANSFERENCIA', 'Bank Transfer')], max_length=20, verbose_name='Method Type')),
                ('name', models.CharField(help_text="E.g., 'Primary Zelle', 'Banesco Mobile Payment'", max_length=100, verbose_name='Account Nickname')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('VEF', 'Venezuelan Bolívar')], editable=False, help_text='The currency in which transactions are made with this method.', max_length=3, verbose_name='Operating Currency')),
                ('details', models.JSONField(default=dict, help_text='Account data will be structured here automatically.', verbose_name='Account Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment methods',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=4, verbose_name='Bank Code')),
                ('name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Bank',
                'verbose_name_plural': 'historical Banks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMethod',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('PAGO_MOVIL', 'Mobile Payment'), ('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('TRANSFERENCIA', 'Bank Transfer')], max_length=20, verbose_name='Method Type')),
                ('name', models.CharField(help_text="E.g., 'Primary Zelle', 'Banesco Mobile Payment'", max_length=100, verbose_name='Account Nickname')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('VEF', 'Venezuelan Bolívar')], editable=False, help_text='The currency in which transactions are made with this method.', max_length=3, verbose_name='Operating Currency')),
                ('details', models.JSONField(default=dict, help_text='Account data will be structured here automatically.', verbose_name='Account Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Payment Method',
                'verbose_name_plural': 'historical Payment methods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_details', models.JSONField(help_text="Details from the user, e.g., {'reference': '123'}", verbose_name='Transaction Details')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('amount_to_pay', models.DecimalField(decimal_places=2, help_text='The final amount the user had to pay, in the currency of the payment method.', max_digits=12, verbose_name='Amount to Pay')),
                ('exchange_rate_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Exchange Rate Applied (VEF per USD)')),
                ('payment_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Payment Hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('ticket_price_at_creation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ticket Price at Creation')),
                ('ticket_count_at_creation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ticket Count at Creation')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='participants.participation', verbose_name='Participation')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
                ('payment_method_used', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.paymentmethod', verbose_name='Payment Method Used')),
            ],
            options={
                'verbose_name': 'historical Payment',
                'verbose_name_plural': 'historical Payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_details', models.JSONField(help_text="Details from the user, e.g., {'reference': '123'}", verbose_name='Transaction Details')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('amount_to_pay', models.DecimalField(decimal_places=2, help_text='The final amount the user had to pay, in the currency of the payment method.', max_digits=12, verbose_name='Amount to Pay')),
                ('exchange_rate_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Exchange Rate Applied (VEF per USD)')),
                ('payment_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Payment Hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('ticket_price_at_creation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ticket Price at Creation')),
                ('ticket_count_at_creation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ticket Count at Creation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='participants.participation', verbose_name='Participation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
                ('payment_method_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod', verbose_name='Payment Method Used')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['status', 'payment_date'], name='payments_pa_status_3f89d4_idx')],
            },
        ),
    ]
