# Generated by Django 5.2.4 on 2025-07-11 17:18

from django.db import migrations

# Lista de bancos a cargar. Mantenerla aquí hace que la migración sea autocontenida.
BANKS_TO_LOAD = [
    ("0102", "BANCO DE VENEZUELA"),
    ("0104", "BANCO VENEZOLANO DE CREDITO"),
    ("0105", "BANCO MERCANTIL"),
    ("0108", "BBVA PROVINCIAL"),
    ("0114", "BANCARIBE"),
    ("0115", "BANCO EXTERIOR"),
    ("0128", "BANCO CARONI"),
    ("0134", "BANESCO"),
    ("0137", "BANCO SOFITASA"),
    ("0138", "BANCO PLAZA"),
    ("0146", "BANGENTE"),
    ("0151", "BANCO FONDO COMUN"),
    ("0156", "100% BANCO"),
    ("0157", "DELSUR BANCO UNIVERSAL"),
    ("0163", "BANCO DEL TESORO"),
    ("0168", "BANCRECER"),
    ("0169", "R4 BANCO MICROFINANCIERO C.A."),
    ("0171", "BANCO ACTIVO"),
    ("0172", "BANCAMIGA BANCO UNIVERSAL, C.A."),
    ("0173", "BANCO INTERNACIONAL DE DESARROLLO"),
    ("0174", "BANPLUS"),
    ("0175", "BANCO DIGITAL DE LOS TRABAJADORES, BANCO UNIVERSAL"),
    ("0177", "BANFANB"),
    ("0178", "N58 BANCO DIGITAL BANCO MICROFINANCIERO S A"),
    ("0191", "BANCO NACIONAL DE CREDITO"),
]


def load_banks(apps, schema_editor):
    """
    Carga la lista inicial de bancos usando update_or_create para ser idempotente.
    """
    # Obtenemos el modelo 'Bank' del estado histórico de las apps para esta migración.
    # ¡No importes el modelo directamente!
    Bank = apps.get_model("payments", "Bank")

    for code, name in BANKS_TO_LOAD:
        Bank.objects.update_or_create(code=code, defaults={"name": name})


def unload_banks(apps, schema_editor):
    """
    Función de reversa: elimina los bancos que se crearon.
    """
    Bank = apps.get_model("payments", "Bank")
    bank_codes = [code for code, name in BANKS_TO_LOAD]
    Bank.objects.filter(code__in=bank_codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_banks, reverse_code=unload_banks),
    ]
