# Generated by Django 5.2.4 on 2025-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cargar_bancos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Bank Code'),
        ),
    ]
